#!/bin/sh

alias ls='eza -al --no-user --no-time -h --icons=always'
alias cd='z'
alias grep='grep --color=auto'
alias wifi='nmcli dev wifi connect'
alias wifilist='nmcli dev wifi list'
alias please='sudo $(fc -ln -1)'
alias gitui='gitui -t mocha.ron'
alias cw='cargo watch -q -c -i static -x run'
alias cwt='cargo watch -q -c -i static -x test'
