#!/bin/sh

# starship
eval "$(starship init zsh)"

# zoxide
eval "$(zoxide init zsh)"

# lf change directory to current directory
LFCD="~/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi
lfcd () {
    # `command` is needed in case `lfcd` is aliased to `lf`
    cd "$(command lf -print-last-dir "$@")"
}
alias lf='lfcd'

# # conda is the absolute worst
# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/johan/.config/conda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/home/johan/.config/conda/etc/profile.d/conda.sh" ]; then
#         . "/home/johan/.config/conda/etc/profile.d/conda.sh"
#     else
#         export PATH="/home/johan/.config/conda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<

# fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
# colors for fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#1e1e2e,bg:#11111b,spinner:#f5e0dc,hl:#f9e2af \
--color=fg:#6c7086,header:#f38ba8,info:#45475a,pointer:#f5e0dc \
--color=fg+:#9399b2,prompt:#f5e0dc,hl+:#fab387 \
--prompt=' ' --color=prompt:#f5e0dc \
--pointer=' ' --color=pointer:#9399b2 \
--color=separator:#1e1e2e,scrollbar:#1e1e2e,query:#cdd6f4 \
--height 50% --layout=reverse \
--preview 'bat -n --color=always {}' \
--preview-window=right,60% \
--preview-window border-sharp --color=border:#1e1e2e \
--border=none "
export FZF_DEFAULT_COMMAND="rg --files --hidden -g '!.git/' -g '!*.cache/'"
export FZF_ALT_C_COMMAND=""
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export DISABLE_AUTO_TITLE=true

# adding python poetry
fpath+=/home/johan/.config/zsh/poetry
autoload -Uz compinit && compinit

# zsh-syntax-highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

source /home/johan/.config/broot/launcher/bash/br

