/*
static const char black[]       = "#1E1D2D";
static const char gray2[]       = "#282737"; // unfocused window border
static const char gray3[]       = "#585767";
static const char gray4[]       = "#282737";
static const char blue[]        = "#96CDFB";  // focused window border
static const char green[]       = "#ABE9B3";
static const char red[]         = "#F28FAD";
static const char orange[]      = "#F8BD96";
static const char yellow[]      = "#FAE3B0";
static const char pink[]        = "#d5aeea";
static const char col_borderbar[]  = "#1E1D2D"; // inner border
static const char white[] = "#f8f8f2";
*/
static const char rosewater[] = "#f5e0dc";
static const char flamingo[] = "#f2cdcd";
static const char pink[] = "#f5c2e7";
static const char mauve[] = "#cba6f7";
static const char red[] = "#f38ba8";
static const char maroon[] = "#eba0ac";
static const char peach[] = "#fab387";
static const char yellow[] = "#f9e2af";
static const char green[] = "#a6e3a1";
static const char teal[] = "#94e2d5";
static const char sky[] = "#89dceb";
static const char sapphire[] = "#74c7ec";
static const char blue[] = "#89b4fa";
static const char lavender[] = "#b4befe";
static const char text[] = "#cdd6f4";
static const char subtext1[] = "#bac2de";
static const char subtext0[] = "#a6adc8";
static const char overlay2[] = "#9399b2";
static const char overlay1[] = "#7f849c";
static const char overlay0[] = "#6c7086";
static const char surface2[] = "#585b70";
static const char surface1[] = "#45475a";
static const char surface0[] = "#313244";
static const char base[] = "#1e1e2e";
static const char mantle[] = "#181825";
static const char crust[] = "#11111b";
