xsetroot -cursor_name left_ptr
xwallpaper --no-randr --stretch "$JOHAN_WALLPAPERS/StarsMocha.png" &
setxkbmap -option caps:escape &
dunst &
a2ln &
# exec clipsim --daemon &
pipewire &
pipewire-pulse &
pipewire-media-session &
dwmblocks &
exec dbus-launch dwm



# exec pipewire &
# exec pipewire-media-session &
# exec pipewire-pulse &

# xwallpaper --stretch "$JOHAN_WALLPAPERS/space.jpg" &
# xwallpaper --stretch "$JOHAN_WALLPAPERS/ThinkPadT480Mocha.png" &


# pipewire-pulse &
# wireplumber &
#
# pipewire &



### Pipewire/Wireplumber notes
# pacman -S pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber
#
# mkdir /etc/pipewire
#
# cp /usr/share/pipewire/pipewire* /etc/pipewire
#
# edit the /etc/pipewire/pipewire.conf file
#
# go to the final option, context.exec = [...]
#
# add the following lines inside the ...
#
# { path = "/usr/bin/wireplumber" args = "" }
# { path = "/usr/bin/pipewire" args = "-c pipewire-pulse.conf" }
#
# it should run pipewire, the pulse layer, and wireplumber to manage the session, all together at once.
