palette = "catppuccin_mocha"
format = """[ ](bg:overlay0 fg:text)\
$time\
[](fg:overlay0 bg:surface2)\
$directory\
[](fg:surface2 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface0)\
$nodejs\
$rust\
$golang\
$php\
[](surface0)\
\n\
[   ](fg:red bg:surface0)\
[ ](surface0)"""

# No new line between shell prompts
add_newline = false

# No line-break between shell prompts
[line_break]
disabled = true


# right_format = """$duration"""

[username]
style_user = 'bg:white bold fg:crust'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
style = "fg:red bg:surface2"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"/documents" =  "/󰈙 documents"
"/Documents" =  "/󰈙 Documents"
"/downloads" =  "/ downloads"
"/Downloads" =  "/ Downloads"
"/music" =      "/ music"
"/Music" =      "/ Music"
"/pictures" =   "/ pictures"
"/Pictures" =   "/ Pictures"
".dotfiles" =   " .dotfiles"
".config" =     " .config"
"/files" =      "/ files"
"/videos" =     "/ videos"
"/youtube" =    "/ youtube"
"/torrents" =   "/ torrents"
"/code" =       "/ code"

[git_branch]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol $branch ](fg:blue bg:surface1)]($style)'

[git_status]
style = "bg:surface1"
format = '[[($all_status$ahead_behind )](fg:blue bg:surface1)]($style)'

[nodejs]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:green bg:surface0)]($style)'

[rust]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:peach bg:surface0)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%H:%M:%S " # Hour:Minute Format
style = "bg:overlay0"
format = '[[$time](fg:text bg:overlay0)]($style)'



[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
