return {
    -- "lvimuser/lsp-inlayhints.nvim",
    -- config = function ()
    --     require("lsp-inlayhints").setup({
    --         inlay_hints = {
    --             parameter_hints = {
    --                 show = true,
    --                 prefix = "<- ",
    --                 separator = ", ",
    --                 remove_colon_start = false,
    --                 remove_colon_end = true,
    --             },
    --             type_hints = {
    --                 show = true,
    --                 prefix = "=> ",
    --                 separator = ", ",
    --                 remove_colon_start = false,
    --                 remove_colon_end = false,
    --             },
    --             only_current_line = false,
    --             -- separator between types and parameter hints. Note that type hints are
    --             -- shown before parameter
    --             labels_separator = " ",
    --             max_len_align = false,
    --             max_len_align_padding = 1,
    --             highlight = "LspInlayHint",
    --             priority = 0,
    --         },
    --
    --     })
    -- end
}
