return {}
-- local rust_tools = require("rust-tools")
-- rust_tools.setup({
--     server = {
--         capabilities = require("cmp_nvim_lsp").default_capabilities(),
--         on_attach = function(_, bufnr)
--             vim.keymap.set("n", "K", rust_tools.hover_actions.hover_actions, { buffer = bufnr })
--             vim.keymap.set("n", "J", rust_tools.join_lines.join_lines)
--             -- vim.keymap.set("n", "<Leader>h", require('rust-tools.inlay_hints').toggle_inlay_hints)
--             vim.keymap.set("n", "<Leader>'", rust_tools.code_action_group.code_action_group, { buffer = bufnr })
--         end,
--     },
--     tools = {
--
--         inlay_hints = {
--             highlight = "RustInlayHints",
--         },
--
--         hover_actions = {
--             auto_focus = false,
--             border = {
--                 { "┌", "Comment" },
--                 { "─", "Comment" },
--                 { "┐", "Comment" },
--                 { "│", "Comment" },
--                 { "┘", "Comment" },
--                 { "─", "Comment" },
--                 { "└", "Comment" },
--                 { "│", "Comment" },
--             }
--         },
--     },
-- })

-- local crates = require("crates")
-- crates.setup()

